AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: description
      SubnetIds: 
        - subnet-0a267d1cc13591e39
        - subnet-0f0620a104759110c
      Tags: 
        - 
          Key: Name
          Value: 'DB subnetgroup'
  MyDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: vpc-002a34ac321708210
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
  MySQLDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: Mysqldb
      DBName: Mysqldb
      DBInstanceClass: db.t3.small
      AllowMajorVersionUpgrade: true
      AllocatedStorage: '20'
      Engine: mysql
        #EngineVersion: "5.7.37"
      EngineVersion: "8.0.28"
      MasterUsername: admin
      MasterUserPassword: 'D0m0re123#'
      PubliclyAccessible: true
      StorageType: 'gp2'
      LicenseModel: 'general-public-license'
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      VPCSecurityGroups:
        - !Ref MyDBSecurityGroup
