AWSTemplateFormatVersion: 2010-09-09
Resources:
  DbOra12cParameter:
    Type: AWS::RDS::DBParameterGroup
    Properties: 
      Description: 'Oracle db parameters'
      Family: 'oracle-se2-12.1'
      Parameters: 
        open_cursors: 400
        optimizer_adaptive_features: false
  MYDBOption:
    Type: "AWS::RDS::OptionGroup"
    Properties: 
      EngineName: oracle-se2
      MajorEngineVersion: "12.1"
      OptionConfigurations: 
        - OptionName: APEX
          OptionVersion: 5.1.4.v1
        - OptionName: APEX-DEV
      OptionGroupDescription: "APEX install option in DB"
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: description
      SubnetIds: 
        - subnet-066e0a92996d907c7
        - subnet-08b435a7a37b11ed0
      Tags: 
        - 
          Key: Name
          Value: DB subnet
  MyDB:
    Type: "AWS::RDS::DBInstance"
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: oradb12c
      DBName: oradb12c
      AllowMajorVersionUgrade: true
      DBInstanceClass: db.t3.small
      AllocatedStorage: 20
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      Engine: oracle-se2
      EngineVersion: 12.1.0.2.v27
      StorageType: gp2
      MasterUsername: admin
      MasterUserPassword: D0m0re1234#
      PubliclyAccessible: True
      LicenseModel: license-included
      OptionGroupName: !Ref MYDBOption
      DBParameterGroupName: !Ref DbOra12cParameter
